### ISSUE TITLE
problem with python install

### ISSUE THREAD

**Issue by Canalytic** [dashpay/electrum-dash#42]
am getting this error when I try to run electrum-dash locally `Traceback (most recent call last):
  File "./electrum-dash", line 47, in <module>
    import google.protobuf
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b3-py2.7.egg/google/__init__.py", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 965, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2626, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2616, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1625, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1617, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1728, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b3-py2.7.egg/EGG-INFO/namespace_packages.txt'
`

when I try via pip I am getting this error: `error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-uTPqGs/hidapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-HKQefz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-uTPqGs/hidapi
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 23: ordinal not in range(128)
'
`

Any idea what I am doing wrong?  Is it a problem with Python?

**Comment by schinzelh** [comment]
What OS, Ubuntu Linux?

**Comment by Kefkius** [comment]
It may be that you're not running 'sudo python setup.py install'

**Comment by Canalytic** [comment]
Ubuntu 15.10.  and when I run 'sudo python setup.py install' I am getting this error: `hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by schinzelh** [comment]
You are missing the libusb-dev package 

Try 

sudo apt-get install libusb-1.0-0-dev libudev-dev

first, then try again

**Comment by Canalytic** [comment]
Thanks schnizelh,

Now I get this: 
`Installed /usr/local/lib/python2.7/dist-packages/Electrum_DASH-2.4.1-py2.7.egg
Processing dependencies for Electrum-DASH==2.4.1
error: protobuf 3.0.0b3 is installed but protobuf==2.6.1 is required by set(['trezor'])
`
