### ISSUE TITLE
AttributeError: module 'electrum_dash.plugins' has no attribute '__file__'

### ISSUE THREAD

**Issue by ghost** [dashpay/electrum-dash#6]
Hello,

if i simply install electrum-dash in a python3.6 venv i get the following error if i try to call it for a new address from the cli with "electrum-dash createnewaddress":

pip install https://github.com/akhavr/electrum-dash/releases/download/3.2.3.2/Dash-Electrum-3.2.3.2.tar.gz#egg=electrum[fast]

full trace

```
Traceback (most recent call last):
  File "/home/claris/Dokumente/PyCharm/echo/venv/bin/electrum-dash", line 474, in <module>
    plugins = init_plugins(config, 'cmdline')
  File "/home/claris/Dokumente/PyCharm/echo/venv/bin/electrum-dash", line 328, in init_plugins
    return Plugins(config, is_local or is_android, gui_name)
  File "/home/claris/Dokumente/PyCharm/echo/venv/lib/python3.6/site-packages/electrum_dash/util.py", line 344, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/claris/Dokumente/PyCharm/echo/venv/lib/python3.6/site-packages/electrum_dash/util.py", line 340, in do_profile
    o = func(*args, **kw_args)
  File "/home/claris/Dokumente/PyCharm/echo/venv/lib/python3.6/site-packages/electrum_dash/plugin.py", line 50, in __init__
    self.pkgpath = os.path.dirname(plugins.__file__)
AttributeError: module 'electrum_dash.plugins' has no attribute '__file__'

```

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
