### ISSUE TITLE
Does not connect to trezor

### ISSUE THREAD

**Issue by dkaparis** [dashpay/electrum-dash#77]
Installed and run current development branch on current Arch Linux system. When opening a trezor hardware wallet, an empty error message box pops up and I get the following output:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_dash_gui/qt/util.py", line 551, in run
    result = task.task()
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1720, in create_next_account
    xpub, xprv = self.derive_xkeys(root_name, derivation, password)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/hw_wallet/hw_wallet.py", line 91, in derive_xkeys
    xpub = self.get_public_key(derivation)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/plugin.py", line 25, in get_public_key
    client = self.get_client()
  File "/usr/lib/python2.7/site-packages/electrum_plugins/hw_wallet/hw_wallet.py", line 77, in get_client
    return self.plugin.get_client(self, force_pair)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/plugin.py", line 138, in get_client
    client = devmgr.client_for_wallet(self, wallet, force_pair)
  File "/usr/lib/python2.7/site-packages/electrum_dash/plugins.py", line 382, in client_for_wallet
    assert wallet.handler
AssertionError
```

If I try to create a new Trezor wallet, I get the error pop up:
"Could not connect to your TREZOR. Verify the cable is connected and that no other application is using it." and no output

The current 2.4.1 release connects to the Trezor without issue on the same system and the Trezor also works with the MyTrezor.com wallet in Chromium.

**Comment by schinzelh** [comment]
Thanks for reporting- it seems the USB code still has some issues...
